export const stations = [

  //METRO

  { id : "01011", name : "Piraeus", eng : "Piraeus"	, sub_agency : "Metro"},
  { id : "01012", name : "Faliro", eng : "Faliro"	, sub_agency : "Metro"},
  { id : "01013", name : "Moschato", eng : "Moschato"	, sub_agency : "Metro"},
  { id : "01014", name : "Kallithea", eng : "Kallithea"	, sub_agency : "Metro"},
  { id : "01015", name : "Tavros", eng : "Tavros"	, sub_agency : "Metro"},
  { id : "01016", name : "Petralona", eng : "Petralona"	, sub_agency : "Metro"},
  { id : "01017", name : "Thiseio", eng : "Thiseio"	, sub_agency : "Metro"},
  { id : "01018", name : "Monastiraki", eng : "Monastiraki"	, sub_agency : "Metro"},
  { id : "01019", name : "Omonia", eng : "Omonia"	, sub_agency : "Metro"},
  { id : "01020", name : "Victoria", eng : "Victoria"	, sub_agency : "Metro"},
  { id : "01021", name : "Attiki", eng : "Attiki"	, sub_agency : "Metro"},
  { id : "01022", name : "Agios Nikolaos", eng : "Agios Nikolaos"	, sub_agency : "Metro"},
  { id : "01023", name : "Kato Patisia", eng : "Kato Patisia"	, sub_agency : "Metro"},
  { id : "01024", name : "Agios Eleftherios", eng : "Agios Eleftherios"	, sub_agency : "Metro"},
  { id : "01025", name : "Ano Patisia", eng : "Ano Patisia"	, sub_agency : "Metro"},
  { id : "01026", name : "Perissos", eng : "Perissos"	, sub_agency : "Metro"},
  { id : "01027", name : "Pefkakia", eng : "Pefkakia"	, sub_agency : "Metro"},
  { id : "01028", name : "Nea Ionia", eng : "Nea Ionia"	, sub_agency : "Metro"},
  { id : "01029", name : "Irakleio", eng : "Irakleio"	, sub_agency : "Metro"},
  { id : "01030", name : "Eirini", eng : "Eirini"	, sub_agency : "Metro"},
  { id : "01031", name : "Marousi", eng : "Marousi"	, sub_agency : "Metro"},
  { id : "01032", name : "KAT", eng : "KAT"	, sub_agency : "Metro"},
  { id : "01033", name : "Kifisia", eng : "Kifisia"	, sub_agency : "Metro"},
  { id : "01034", name : "Anthoupoli", eng : "Anthoupoli"	, sub_agency : "Metro"},
  { id : "01035", name : "Peristeri", eng : "Peristeri"	, sub_agency : "Metro"},
  { id : "01036", name : "Agios Antonios", eng : "Agios Antonios"	, sub_agency : "Metro"},
  { id : "01037", name : "Sepolla", eng : "Sepolla"	, sub_agency : "Metro"},
  { id : "01038", name : "Attiki", eng : "Attiki"	, sub_agency : "Metro"},
  { id : "01039", name : "Larissa Station", eng : "Larissa Station"	, sub_agency : "Metro"},
  { id : "01040", name : "Metaxourghio", eng : "Metaxourghio"	, sub_agency : "Metro"},
  { id : "01041", name : "Panepistimio", eng : "Panepistimio"	, sub_agency : "Metro"},
  { id : "01042", name : "Syntagma", eng : "Syntagma"	, sub_agency : "Metro"},
  { id : "01043", name : "Akropoli", eng : "Akropoli"	, sub_agency : "Metro"},
  { id : "01044", name : "Syngrou Fix", eng : "Syngrou Fix"	, sub_agency : "Metro"},
  { id : "01045", name : "Neos Kosmos", eng : "Neos Kosmos"	, sub_agency : "Metro"},
  { id : "01046", name : "Agios Loannis", eng : "Agios Loannis"	, sub_agency : "Metro"},
  { id : "01047", name : "Dafni", eng : "Dafni"	, sub_agency : "Metro"},
  { id : "01048", name : "Agios Dimitrios", eng : "Agios Dimitrios"	, sub_agency : "Metro"},
  { id : "01049", name : "llioupoli", eng : "llioupoli"	, sub_agency : "Metro"},
  { id : "01050", name : "Alimos", eng : "Alimos"	, sub_agency : "Metro"},
  { id : "01051", name : "Argyroupoli", eng : "Argyroupoli"	, sub_agency : "Metro"},
  { id : "01052", name : "Elliniko", eng : "Elliniko"	, sub_agency : "Metro"},
  { id : "01053", name : "Agia Marina", eng : "Agia Marina"	, sub_agency : "Metro"},
  { id : "01054", name : "Egaleo", eng : "Egaleo"	, sub_agency : "Metro"},
  { id : "01055", name : "Eleonas", eng : "Eleonas"	, sub_agency : "Metro"},
  { id : "01056", name : "Kerameikos", eng : "Kerameikos"	, sub_agency : "Metro"},
  { id : "01057", name : "Monastiraki", eng : "Monastiraki"	, sub_agency : "Metro"},
  { id : "01058", name : "Syntagma", eng : "Syntagma"	, sub_agency : "Metro"},
  { id : "01059", name : "Evangelismos", eng : "Evangelismos"	, sub_agency : "Metro"},
  { id : "01060", name : "Megaro Moussikis", eng : "Megaro Moussikis"	, sub_agency : "Metro"},
  { id : "01061", name : "Ambeiokipi", eng : "Ambeiokipi"	, sub_agency : "Metro"},
  { id : "01062", name : "Panormou", eng : "Panormou"	, sub_agency : "Metro"},
  { id : "01063", name : "Katehaki", eng : "Katehaki"	, sub_agency : "Metro"},
  { id : "01064", name : "Ethniki Amyna", eng : "Ethniki Amyna"	, sub_agency : "Metro"},
  { id : "01065", name : "Holargos", eng : "Holargos"	, sub_agency : "Metro"},
  { id : "01066", name : "Nomismatokipio", eng : "Nomismatokipio"	, sub_agency : "Metro"},
  { id : "01067", name : "Agia Paraskevi", eng : "Agia Paraskevi"	, sub_agency : "Metro"},
  { id : "01068", name : "Chalandri", eng : "Chalandri"	, sub_agency : "Metro"},
  { id : "01069", name : "Doukissis Plakentias", eng : "Doukissis Plakentias"	, sub_agency : "Metro"},
  { id : "01070", name : "Pallini", eng : "Pallini"	, sub_agency : "Metro"},
  { id : "01071", name : "Paiania-Kantza", eng : "Paiania-Kantza"	, sub_agency : "Metro"},
  { id : "01072", name : "Athens International Airport", eng : "Athens International Airport"	, sub_agency : "Metro"},


//SUBURBAΝ

  { id : "02001", name : "ΑΕΡΟΔΡΟΜΙΟ", eng : "AIRPORT1", sub_agency : "Suburban"},
  { id : "02002", name : "ΚΟΡΩΠΙ", eng : "KOROPI", sub_agency : "Suburban"},
  { id : "02003", name : "ΠΑΙΑΝΙΑ - ΚΑΝΤΖΑ", eng : "PAIANIA - KANTZA", sub_agency : "Suburban"},
  { id : "02004", name : "ΠΑΛΛΗΝΗ", eng : "PALLINI", sub_agency : "Suburban"},
  { id : "02005", name : "Δ. ΠΛΑΚΕΝΤΙΑΣ", eng : "D. PLAKENTIAS", sub_agency : "Suburban"},
  { id : "02006", name : "ΠΕΝΤΕΛΗΣ", eng : "PENTELIS", sub_agency : "Suburban"},
  { id : "02007", name : "ΚΗΦΙΣΙΑΣ", eng : "KIFISSIAS", sub_agency : "Suburban"},
  { id : "02008", name : "ΝΕΡΑΤΖΙΩΤΙΣΣΑ", eng : "NERATZIOTISSA", sub_agency : "Suburban"},
  { id : "02009", name : "ΗΡΑΚΛΕΙΟ", eng : "IRAKLIO", sub_agency : "Suburban"},
  { id : "02010", name : "ΜΕΤΑΜΟΡΦΩΣΗ", eng : "METAMORFOSI", sub_agency : "Suburban"},
  { id : "02011", name : "ΣΚΑ", eng : "SKA", sub_agency : "Suburban"},
  { id : "02012", name : "ΑΝΩ ΛΙΟΣΙΑ", eng : "ΑΝΟ LIOSIA", sub_agency : "Suburban"},
  { id : "02013", name : "ΑΣΠΡΟΠΥΡΓΟΣ", eng : "ASPROPYRGOS", sub_agency : "Suburban"},
  { id : "02014", name : "ΜΑΓΟΥΛΑ", eng : "MAGOULA", sub_agency : "Suburban"},
  { id : "02015", name : "ΝΕΑ ΠΕΡΑΜΟΣ", eng : "NEA PERAMOS", sub_agency : "Suburban"},
  { id : "02016", name : "ΜΕΓΑΡΑ", eng : "MEGARA", sub_agency : "Suburban"},
  { id : "02017", name : "ΚΙΝΕΤΤΑ", eng : "KINETTA", sub_agency : "Suburban"},
  { id : "02018", name : "ΑΓ. ΘΕΟΔΩΡΟΙ", eng : "AG. THEODOROI", sub_agency : "Suburban"},
  { id : "02019", name : "ΚΟΡΙΝΘΟΣ", eng : "KORINTHOS", sub_agency : "Suburban"},
  { id : "02020", name : "ΖΕΥΓΟΛΑΤΙΟ", eng : "ZEVGOLATIO", sub_agency : "Suburban"},
  { id : "02021", name : "KIATO", eng : "KIATO", sub_agency : "Suburban"},
  { id : "02101", name : "ΠΕΙΡΑΙΑΣ", eng : "PIRAEUS", sub_agency : "Suburban"},
  { id : "02102", name : "ΛΕΥΚΑ", eng : "LEFKA", sub_agency : "Suburban"},
  { id : "02103", name : "ΡΕΝΤΗΣ", eng : "RENTIS", sub_agency : "Suburban"},
  { id : "02104", name : "ΤΑΥΡΟΣ", eng : "TAVROS", sub_agency : "Suburban"},
  { id : "02105", name : "ΡΟΥΦ", eng : "ROUF", sub_agency : "Suburban"},
  { id : "02106", name : "ΑΘΗΝΑ", eng : "ATHENS", sub_agency : "Suburban"},
  { id : "02107", name : "ΑΓ. ΑΝΑΡΓΥΡΟΙ", eng : "AG. ANARGYROI", sub_agency : "Suburban"},
  { id : "02108", name : "ΠΥΡΓΟΣ ΒΑΣΙΛΙΣΣΗΣ", eng : "PIRGOS VASILISSIS", sub_agency : "Suburban"},
  { id : "02109", name : "ΚΑΤΩ ΑΧΑΡΝΑΙ", eng : "ΚΑΤΟ ACHARNAI", sub_agency : "Suburban"},
  { id : "02110", name : "ΣΚΑ - ΑΧΑΡΝΑΙ", eng : "SKA - ACHARNAI", sub_agency : "Suburban"},
  { id : "02111", name : "ΑΧΑΡΝΕΣ", eng : "ACHARNES", sub_agency : "Suburban"},
  { id : "02112", name : "ΔΕΚΕΛΕΙΑ", eng : "DEKELEIA", sub_agency : "Suburban"},
  { id : "02113", name : "ΑΓ. ΣΤΕΦΑΝΟΣ", eng : "AG. STEFANOS", sub_agency : "Suburban"},
  { id : "02114", name : "ΑΦΙΔΝΕΣ", eng : "AFIDNES", sub_agency : "Suburban"},
  { id : "02115", name : "ΣΦΕΝΔΑΛΗ", eng : "SFENDALI", sub_agency : "Suburban"},
  { id : "02116", name : "ΑΥΛΩΝΑΣ", eng : "AVLONAS", sub_agency : "Suburban"},
  { id : "02117", name : "ΑΓΙΟΣ ΘΩΜΑΣ", eng : "AGIOS THOMAS", sub_agency : "Suburban"},
  { id : "02118", name : "ΟΙΝΟΦΥΤΑ", eng : "OINOFYTA", sub_agency : "Suburban"},
  { id : "02119", name : "ΟΙΝΟΗ", eng : "INOI", sub_agency : "Suburban"},
  { id : "02120", name : "ΔΗΛΕΣΙ", eng : "DILESI", sub_agency : "Suburban"},
  { id : "02121", name : "ΑΓ. ΓΕΩΡΓΙΟΣ", eng : "AG. GEORGIOS", sub_agency : "Suburban"},
  { id : "02122", name : "ΚΑΛΟΧΩΡΙ", eng : "KALOHORI", sub_agency : "Suburban"},
  { id : "02123", name : "ΑΥΛΙΔΑ", eng : "AVLIDA", sub_agency : "Suburban"},
  { id : "02124", name : "ΝΑΥΠΗΓΕΙΑ", eng : "NAFPIGIA", sub_agency : "Suburban"},
  { id : "02125", name : "ΣΤΕΝΟ", eng : "STENO", sub_agency : "Suburban"},
  { id : "02126", name : "ΧΑΛΚΙΔΑ", eng : "CHALKIDA", sub_agency : "Suburban"},


//Tram

  { id : "0001", name : "Σ.Ε.Φ.-ΣΤΑΔΙΟ ΕΙΡΗΝΗΣ&ΦΙΛΙΑΣ", sub_agency : "Tram" },
  { id : "0002", name : "ΝΕΟ ΦΑΛΗΡΟ", sub_agency : "Tram" },
  { id : "0003", name : "ΜΟΣΧΑΤΟ", sub_agency : "Tram" },
  { id : "0004", name : "ΚΑΛΛΙΘΕΑ", sub_agency : "Tram" },
  { id : "0005", name : "ΤΖΙΤΖΙΦΙΕΣ", sub_agency : "Tram" },
  { id : "0006", name : "ΔΕΛΤΑ ΦΑΛΗΡΟΥ", sub_agency : "Tram" },
  { id : "0007", name : "ΑΓΙΑ ΣΚΕΠΗ", sub_agency : "Tram" },
  { id : "0008", name : "ΤΡΟΚΑΝΤΕΡΟ", sub_agency : "Tram" },
  { id : "0009", name : "ΠΑΡΚΟ ΦΛΟΙΣΒΟΥ", sub_agency : "Tram" },
  { id : "0010", name : "ΦΛΟΙΣΒΟΣ", sub_agency : "Tram" },
  { id : "0011", name : "ΜΠΑΤΗΣ", sub_agency : "Tram" },
  { id : "0029", name : "ΕΔΕΜ", sub_agency : "Tram" },
  { id : "0030", name : "ΠΙΚΡΟΔΑΦΝΗ", sub_agency : "Tram" },
  { id : "0031", name : "ΜΑΡΙΝΑ ΑΛΙΜΟΥ", sub_agency : "Tram" },
  { id : "0032", name : "ΚΑΛΑΜΑΚΙ", sub_agency : "Tram" },
  { id : "0033", name : "ΖΕΦΥΡΟΣ", sub_agency : "Tram" },
  { id : "0034", name : "ΛΟΥΤΡΑ ΑΛΙΜΟΥ", sub_agency : "Tram" },
  { id : "0035", name : "ΕΛΛΗΝΙΚΟ", sub_agency : "Tram" },
  { id : "0036", name : "1Η ΑΓ.ΚΟΣΜΑ", sub_agency : "Tram" },
  { id : "0037", name : "2Η ΑΓ.ΚΟΣΜΑ", sub_agency : "Tram" },
  { id : "0038", name : "ΑΓΙΟΣ ΑΛΕΞΑΝΔΡΟΣ", sub_agency : "Tram" },
  { id : "0039", name : "ΕΛΛΗΝΩΝ ΟΛΥΜΠΙΟΝΙΚΩΝ", sub_agency : "Tram" },
  { id : "0040", name : "ΚΕΝΤΡΟ ΙΣΤΙΟΠΛΟΙΑΣ", sub_agency : "Tram" },
  { id : "0041", name : "ΠΛΑΤΕΙΑ ΒΕΡΓΩΤΗ", sub_agency : "Tram" },
  { id : "0042", name : "ΠΑΡΑΛΙΑ ΓΛΥΦΑΔΑΣ", sub_agency : "Tram" },
  { id : "0043", name : "ΠΑΛΑΙΟ ΔΗΜΑΡΧΕΙΟ", sub_agency : "Tram" },
  { id : "0044", name : "ΠΛΑΤΕΙΑ ΚΑΤΡΑΚΗ", sub_agency : "Tram" },
  { id : "0045", name : "ΑΓΓΕΛΟΥ ΜΕΤΑΞΑ", sub_agency : "Tram" },
  { id : "0046", name : "ΠΛΑΤΕΙΑ ΕΣΠΕΡΙΔΩΝ", sub_agency : "Tram" },
  { id : "0047", name : "ΚΟΛΥΜΒΗΤΗΡΙΟ", sub_agency : "Tram" },
  { id : "0048", name : "ΑΣΚΛΗΠΙΕΙΟ ΒΟΥΛΑΣ", sub_agency : "Tram" },
  { id : "0001", name : "Σ.Ε.Φ.-ΣΤΑΔΙΟ ΕΙΡΗΝΗΣ&ΦΙΛΙΑΣ", sub_agency : "Tram" },
  { id : "0012", name : "ΣΥΝΤΑΓΜΑ", sub_agency : "Tram" },
  { id : "0013", name : "ΖΑΠΠΕΙΟ", sub_agency : "Tram" },
  { id : "0014", name : "ΛΕΩΦ.ΒΟΥΛΙΑΓΜΕΝΗΣ", sub_agency : "Tram" },
  { id : "0015", name : "ΦΙΞ", sub_agency : "Tram" },
  { id : "0016", name : "ΚΑΣΟΜΟΥΛΗ", sub_agency : "Tram" },
  { id : "0017", name : "ΝΕΟΣ ΚΟΣΜΟΣ", sub_agency : "Tram" },
  { id : "0018", name : "ΜΠΑΚΝΑΝΑ", sub_agency : "Tram" },
  { id : "0019", name : "ΑΙΓΑΙΟΥ", sub_agency : "Tram" },
  { id : "0020", name : "ΑΓΙΑΣ ΦΩΤΕΙΝΗΣ", sub_agency : "Tram" },
  { id : "0021", name : "ΜΕΓΑΛΟΥ ΑΛΕΞΑΝΔΡΟΥ", sub_agency : "Tram" },
  { id : "0022", name : "ΑΓΙΑ ΠΑΡΑΣΚΕΥΗ", sub_agency : "Tram" },
  { id : "0023", name : "ΜΗΔΕΙΑΣ-ΜΥΚΑΛΗΣ", sub_agency : "Tram" },
  { id : "0024", name : "ΕΥΑΓΓΕΛΙΚΗ ΣΧΟΛΗ", sub_agency : "Tram" },
  { id : "0025", name : "ΑΧΙΛΛΕΩΣ", sub_agency : "Tram" },
  { id : "0026", name : "ΑΜΦΙΘΕΑΣ", sub_agency : "Tram" },
  { id : "0027", name : "ΠΑΝΑΓΙΤΣΑ", sub_agency : "Tram" },
  { id : "0028", name : "ΜΟΥΣΩΝ", sub_agency : "Tram" },
  { id : "0011", name : "ΜΠΑΤΗΣ", sub_agency : "Tram" },
  { id : "0010", name : "ΦΛΟΙΣΒΟΣ", sub_agency : "Tram" },
  { id : "0009", name : "ΠΑΡΚΟ ΦΛΟΙΣΒΟΥ", sub_agency : "Tram" },
  { id : "0008", name : "ΤΡΟΚΑΝΤΕΡΟ", sub_agency : "Tram" },
  { id : "0007", name : "ΑΓΙΑ ΣΚΕΠΗ", sub_agency : "Tram" },
  { id : "0006", name : "ΔΕΛΤΑ ΦΑΛΗΡΟΥ", sub_agency : "Tram" },
  { id : "0005", name : "ΤΖΙΤΖΙΦΙΕΣ", sub_agency : "Tram" },
  { id : "0004", name : "ΚΑΛΛΙΘΕΑ", sub_agency : "Tram" },
  { id : "0003", name : "ΜΟΣΧΑΤΟ", sub_agency : "Tram" },
  { id : "0002", name : "ΝΕΟ ΦΑΛΗΡΟ", sub_agency : "Tram" },
  { id : "0001", name : "Σ.Ε.Φ.-ΣΤΑΔΙΟ ΕΙΡΗΝΗΣ&ΦΙΛΙΑΣ", sub_agency : "Tram" },
  { id : "0012", name : "ΣΥΝΤΑΓΜΑ", sub_agency : "Tram" },
  { id : "0013", name : "ΖΑΠΠΕΙΟ", sub_agency : "Tram" },
  { id : "0014", name : "ΛΕΩΦ.ΒΟΥΛΙΑΓΜΕΝΗΣ", sub_agency : "Tram" },
  { id : "0015", name : "ΦΙΞ", sub_agency : "Tram" },
  { id : "0016", name : "ΚΑΣΟΜΟΥΛΗ", sub_agency : "Tram" },
  { id : "0017", name : "ΝΕΟΣ ΚΟΣΜΟΣ", sub_agency : "Tram" },
  { id : "0018", name : "ΜΠΑΚΝΑΝΑ", sub_agency : "Tram" },
  { id : "0019", name : "ΑΙΓΑΙΟΥ", sub_agency : "Tram" },
  { id : "0020", name : "ΑΓΙΑΣ ΦΩΤΕΙΝΗΣ", sub_agency : "Tram" },
  { id : "0021", name : "ΜΕΓΑΛΟΥ ΑΛΕΞΑΝΔΡΟΥ", sub_agency : "Tram" },
  { id : "0022", name : "ΑΓΙΑ ΠΑΡΑΣΚΕΥΗ", sub_agency : "Tram" },
  { id : "0023", name : "ΜΗΔΕΙΑΣ-ΜΥΚΑΛΗΣ", sub_agency : "Tram" },
  { id : "0024", name : "ΕΥΑΓΓΕΛΙΚΗ ΣΧΟΛΗ", sub_agency : "Tram" },
  { id : "0025", name : "ΑΧΙΛΛΕΩΣ", sub_agency : "Tram" },
  { id : "0026", name : "ΑΜΦΙΘΕΑΣ", sub_agency : "Tram" },
  { id : "0027", name : "ΠΑΝΑΓΙΤΣΑ", sub_agency : "Tram" },
  { id : "0028", name : "ΜΟΥΣΩΝ", sub_agency : "Tram" },
  { id : "0029", name : "ΕΔΕΜ", sub_agency : "Tram" },
  { id : "0030", name : "ΠΙΚΡΟΔΑΦΝΗ", sub_agency : "Tram" },
  { id : "0031", name : "ΜΑΡΙΝΑ ΑΛΙΜΟΥ", sub_agency : "Tram" },
  { id : "0032", name : "ΚΑΛΑΜΑΚΙ", sub_agency : "Tram" },
  { id : "0033", name : "ΖΕΦΥΡΟΣ", sub_agency : "Tram" },
  { id : "0034", name : "ΛΟΥΤΡΑ ΑΛΙΜΟΥ", sub_agency : "Tram" },
  { id : "0035", name : "ΕΛΛΗΝΙΚΟ", sub_agency : "Tram" },
  { id : "0036", name : "1Η ΑΓ.ΚΟΣΜΑ", sub_agency : "Tram" },
  { id : "0037", name : "2Η ΑΓ.ΚΟΣΜΑ", sub_agency : "Tram" },
  { id : "0038", name : "ΑΓΙΟΣ ΑΛΕΞΑΝΔΡΟΣ", sub_agency : "Tram" },
  { id : "0039", name : "ΕΛΛΗΝΩΝ ΟΛΥΜΠΙΟΝΙΚΩΝ", sub_agency : "Tram" },
  { id : "0040", name : "ΚΕΝΤΡΟ ΙΣΤΙΟΠΛΟΙΑΣ", sub_agency : "Tram" },
  { id : "0041", name : "ΠΛΑΤΕΙΑ ΒΕΡΓΩΤΗ", sub_agency : "Tram" },
  { id : "0042", name : "ΠΑΡΑΛΙΑ ΓΛΥΦΑΔΑΣ", sub_agency : "Tram" },
  { id : "0043", name : "ΠΑΛΑΙΟ ΔΗΜΑΡΧΕΙΟ", sub_agency : "Tram" },
  { id : "0044", name : "ΠΛΑΤΕΙΑ ΚΑΤΡΑΚΗ", sub_agency : "Tram" },
  { id : "0045", name : "ΑΓΓΕΛΟΥ ΜΕΤΑΞΑ", sub_agency : "Tram" },
  { id : "0046", name : "ΠΛΑΤΕΙΑ ΕΣΠΕΡΙΔΩΝ", sub_agency : "Tram" },
  { id : "0047", name : "ΚΟΛΥΜΒΗΤΗΡΙΟ", sub_agency : "Tram" },
  { id : "0048", name : "ΑΣΚΛΗΠΙΕΙΟ ΒΟΥΛΑΣ", sub_agency : "Tram" },





];
